# Site settings
title: ePortfolio
email: tompchristian123@gmail.com
description: ""
keywords: ""
skills: "Full-Stack Developer - UI/UX Designer - Software Engineer"
meta_author: Christian Thomas
name: Thomas Christian
# url: https://github.com/jeromelachaud/freelancer-theme

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form removed as requested
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c 
  primary-rgb: "24,288,156" 
  secondary: 2c3e50 
  secondary-dark: 233140 

# Footer settings
footer:
  social: Links


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fa-brands fa-fw fa-linkedin
    url: https://www.linkedin.com/in/tompchristian/
  - title: fa-brands fa-fw fa-github
    url: https://github.com/Thomas-Christian
  - title: fa-solid fa-envelope
    url: mailto:tompchristian123@gmail.com


# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""